# Generated by Django 4.2.2 on 2023-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.png", null=True, upload_to=""),
        ),
    ]
