# Generated by Django 4.2.2 on 2023-11-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="payloads",
        ),
        migrations.AlterField(
            model_name="payloads",
            name="sensor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payload_set",
                to="dashboard.sensor",
            ),
        ),
    ]
