# Generated by Django 4.2.2 on 2023-07-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_todoapp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoapp",
            options={"verbose_name_plural": "Todo App"},
        ),
        migrations.AddField(
            model_name="todoapp",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
