# Generated by Django 4.2.2 on 2023-11-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_remove_sensor_payloads_alter_payloads_sensor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldSensorQr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_qr",
                    models.CharField(blank=True, max_length=27, null=True, unique=True),
                ),
                (
                    "sensor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.sensor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sold Sensors Qr Code",
            },
        ),
        migrations.CreateModel(
            name="UnSoldSensorQr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_qr",
                    models.CharField(blank=True, max_length=27, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Unsold Sensors Qr Code",
            },
        ),
        migrations.AlterField(
            model_name="payloads",
            name="humidity",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="payloads",
            name="soil_moisture",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="payloads",
            name="temperature",
            field=models.FloatField(default=1.0),
        ),
        migrations.DeleteModel(
            name="SensorQr",
        ),
    ]
