# Generated by Django 4.2.2 on 2023-07-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_todoapp_options_todoapp_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoapp",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
