# Generated by Django 4.2.2 on 2023-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_todoapp_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoapp",
            name="done",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
