# Generated by Django 4.2.2 on 2023-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_remove_soldsensorqr_sensor_qr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soldsensorqr",
            name="qr",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
