# Generated by Django 4.2.2 on 2023-11-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_remove_soldsensorqr_qr_soldsensorqr_sensor_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unsoldsensorqr",
            name="sensor_qr",
        ),
        migrations.AddField(
            model_name="unsoldsensorqr",
            name="unsold_sensor_qr",
            field=models.CharField(blank=True, max_length=27, null=True, unique=True),
        ),
    ]
