# Generated by Django 4.2.2 on 2023-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_todoapp_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoapp",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
