# Generated by Django 4.2.2 on 2023-07-18 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_todoapp_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoapp",
            name="time",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
