# Generated by Django 4.2.2 on 2023-07-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_todoapp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
