# Generated by Django 4.2.2 on 2023-07-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_todoapp_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor')),
            ],
        ),
    ]
