# Generated by Django 4.2.2 on 2023-12-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_payloads_humidity_alter_payloads_soil_moisture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_marketing_mails',
            field=models.BooleanField(default=False),
        ),
    ]
