# Generated by Django 4.2.2 on 2023-07-22 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_sensorsqr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airhumidity',
            options={'verbose_name_plural': 'Air Humidity'},
        ),
        migrations.AlterModelOptions(
            name='airhumiditymineralcontent',
            options={'verbose_name_plural': 'Air Humidity Mineral Content'},
        ),
        migrations.AlterModelOptions(
            name='payloads',
            options={'verbose_name_plural': 'Payloads'},
        ),
        migrations.AlterModelOptions(
            name='phlevel',
            options={'verbose_name_plural': 'Ph Level'},
        ),
        migrations.AlterModelOptions(
            name='phlevelmineralcontent',
            options={'verbose_name_plural': 'Ph Level Mineral Content'},
        ),
        migrations.AlterModelOptions(
            name='salinity',
            options={'verbose_name_plural': 'Salinity'},
        ),
        migrations.AlterModelOptions(
            name='salinitymineralcontent',
            options={'verbose_name_plural': 'Salinity Mineral Content'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='sensorsqr',
            options={'verbose_name_plural': 'Sensors QR'},
        ),
        migrations.AlterModelOptions(
            name='soilmoisture',
            options={'verbose_name_plural': 'Soil Moisture'},
        ),
        migrations.AlterModelOptions(
            name='soilmoisturemineralcontent',
            options={'verbose_name_plural': 'Soil Moisture Mineral Content'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='sensorsqr',
            name='sensor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_qr', to='dashboard.sensor'),
        ),
    ]
