# Generated by Django 4.2.2 on 2023-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_airhumidity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorsqr',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_qr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
