# Generated by Django 4.2.2 on 2023-07-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_sensorsqr_sensor_sensor_sensor_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_qr', models.CharField(blank=True, max_length=30, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Sensor Qr Code',
            },
        ),
        migrations.DeleteModel(
            name='SensorsQR',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_qr',
        ),
        migrations.AddField(
            model_name='sensorqr',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor'),
        ),
    ]
