# Generated by Django 4.2.2 on 2023-07-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_sensorqr_delete_sensorsqr_remove_sensor_sensor_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorqr',
            name='sensor_qr',
            field=models.CharField(blank=True, max_length=27, null=True, unique=True),
        ),
    ]
