# Generated by Django 4.2.2 on 2023-07-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_sensorqr_sensor_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorqr',
            name='sensor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor'),
        ),
    ]
