# Generated by Django 4.2.2 on 2023-07-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_sensorqr_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='token',
            field=models.CharField(blank=True, default='No Location Added', max_length=100, null=True),
        ),
    ]
