# Generated by Django 4.2.2 on 2023-10-28 23:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_sensor_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airhumidity',
            name='payload',
        ),
        migrations.DeleteModel(
            name='AirHumidityMineralContent',
        ),
        migrations.RemoveField(
            model_name='phlevel',
            name='payload',
        ),
        migrations.DeleteModel(
            name='PhLevelMineralContent',
        ),
        migrations.RemoveField(
            model_name='salinity',
            name='payload',
        ),
        migrations.DeleteModel(
            name='SalinityMineralContent',
        ),
        migrations.RemoveField(
            model_name='soilmoisture',
            name='payload',
        ),
        migrations.DeleteModel(
            name='SoilMoistureMineralContent',
        ),
        migrations.AddField(
            model_name='payloads',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payloads',
            name='sensor_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payloads',
            name='soil_moisture',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payloads',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payloads',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='payloads',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_payload', to='dashboard.payloads'),
        ),
        migrations.AlterField(
            model_name='payloads',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='dashboard.sensor'),
        ),
        migrations.DeleteModel(
            name='AirHumidity',
        ),
        migrations.DeleteModel(
            name='PhLevel',
        ),
        migrations.DeleteModel(
            name='Salinity',
        ),
        migrations.DeleteModel(
            name='SoilMoisture',
        ),
    ]
